version: '3.9'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres-data:
